image: gentoo/stage3-amd64:latest

pages:
  stage: deploy
  script:
  - mkdir -p /var/cache/binpkgs
  - mkdir -p /var/cache/distfiles
  - mkdir -p /var/db/repos/gentoo
  - mkdir -p /etc/portage/repos.conf
  - emerge-webrsync
  - export PORTAGE_BINHOST="https://xgqt.gitlab.io/gentoo-mini-mirror/binpkgs"
  - export FEATURES="getbinpkg"
  - export MAKEOPTS="--jobs=10"
  - export USE="-perl"
  - emerge -1nq --jobs=10 app-portage/gentoolkit app-portage/repoman app-eselect/eselect-repository dev-vcs/git sys-apps/busybox
  - eselect repository enable src_prepare-overlay
  - emaint sync -r src_prepare-overlay
  - echo '*/*::src_prepare-overlay **' > /etc/portage/package.accept_keywords
  - emerge -1nq --jobs=10 app-portage/euscan-ng
  - sh ./gen-pkgs.sh
  artifacts:
    paths:
    - public
  only:
  - master
