---


# This file is part of gen-pkgs.

# gen-pkgs is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# gen-pkgs is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with gen-pkgs.  If not, see <https://www.gnu.org/licenses/>.


image: gentoo/stage3-amd64:latest


variables:
  FEATURES: "getbinpkg"
  GIT_SUBMODULE_STRATEGY: recursive
  MAKEOPTS: "--jobs=10"
  PORTAGE_BINHOST: "https://xgqt.gitlab.io/gentoo-mini-mirror/binpkgs"
  USE: "-perl"


before_script:
  - mkdir -p /var/cache/binpkgs
  - mkdir -p /var/cache/distfiles
  - mkdir -p /var/db/repos/gentoo
  - mkdir -p /etc/portage/repos.conf
  - emerge-webrsync
  - emerge -1nq --jobs=10 app-portage/gentoolkit app-portage/repoman dev-vcs/git sys-apps/busybox
  - sh ./install-overlay.sh "https://gitlab.com/src_prepare/src_prepare-overlay"
  - echo '*/*::src_prepare-overlay **' >> /etc/portage/package.accept_keywords
  - emerge -1nq --jobs=10 app-portage/euscan-ng


pages:
  stage: deploy
  script:
    - sh ./gen-pkgs.sh -n "/var/db/repos/src_prepare-overlay"
  artifacts:
    paths:
      - public
  only:
    - master
